# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Upload Node Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: package.json

      - name: Upload Client Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: client/build

      - name: Upload Server Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: server-build
          path: server/build

      - name: Upload Server package.json
        uses: actions/upload-artifact@v3
        with:
          name: server-app
          path: server/package.json

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download App Artifacts
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Download Client Build Folder
        uses: actions/download-artifact@v3
        with:
          name: client-build
          path: client/build

      - name: Download Server Build Folder
        uses: actions/download-artifact@v3
        with:
          name: server-build
          path: server/build

      - name: Download Server package.json
        uses: actions/download-artifact@v3
        with:
          name: server-app
          path: server

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mapleriverbasketball'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_725A7776FF3A481CB7B0C252AFBE1432 }}
          package: .
